server.port=7501

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Kyc_Db
spring.datasource.username=postgres
spring.datasource.password=9305

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (optional but good practice)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# File Storage Path
file.upload-dir=C:/Users/Asus/Desktop/Payment-end/kyc_uploads

# Swagger / OpenAPI Config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Custom path (optional)
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
