
server.port= 7500

spring.datasource.url=jdbc:postgresql://localhost:5432/User_Db
spring.datasource.username=postgres
spring.datasource.password=9305

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey
jwt.expiration=3600000

# ===============================
# MAIL CONFIG (SMTP - Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srivastavaharsh148@gmail.com
spring.mail.password=jqsm stiv wzgb nhei

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# SWAGGER (SPRINGDOC OPENAPI)
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# FUTURE CONFIG (OTP / RATE LIMIT)
# ===============================
otp.expiry=300000
otp.max-attempts=5

rate.limit.requests=5
rate.limit.duration=60
